name: ci
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  dzil_test_release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        perl: [ '5.26', '5.28', '5.30' ]
    container: perl:${{ matrix.perl }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          cpanm --quiet --notest \
            App::FatPacker \
            Dist::Zilla \
            Perl::Critic \
            Perl::Tidy \
            File::Slurp \
            Perl::Stripper
          dzil authordeps | xargs cpanm --quiet --notest && \
          dzil listdeps --develop | xargs cpanm --quiet --notest

      - name: Test release
        run: dzil test --release
