name: deb package
on:
  push:
  workflow_dispatch:

jobs:
  dzil_build:
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    runs-on: ubuntu-latest
    container: perl:5.30
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          cpanm --quiet --notest \
            App::FatPacker \
            Dist::Zilla \
            Perl::Critic \
            Perl::Tidy \
            File::Slurp \
            Perl::Stripper
          dzil authordeps | xargs cpanm --quiet --notest && \
          dzil listdeps --develop | xargs cpanm --quiet --notest

      - name: fatpack App::* as well
        run: sed -i '/exclude_pattern/d' depak.conf

      - name: Build release
        run: dzil install && dzil clean && dzil build

      - run: echo "VERSION=$(git describe --tags `git rev-list --tags --max-count=1`)" >> $GITHUB_ENV

      - name: Upload fatpacked artifact
        uses: actions/upload-artifact@v2
        with:
          name: fatpacked_artifact
          path: nioscli-${{ env.VERSION }}/bin/nioscli
          if-no-files-found: error
          retention-days: 1
  deb:
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    needs: [dzil_build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Download fatpacked artifact
        uses: actions/download-artifact@v2
        with:
          name: fatpacked_artifact
          path: release/nioscli

      - run: echo "VERSION=$(git describe --tags `git rev-list --tags --max-count=1`)" >> $GITHUB_ENV

      - name: Create build directory tree
        run: |
          mkdir -p debian_build_directory/nioscli
          mkdir -p debian_build_directory/nioscli/DEBIAN
          mkdir -p debian_build_directory/nioscli/usr/bin
          cp release/nioscli/nioscli debian_build_directory/nioscli/usr/bin
          chmod +x debian_build_directory/nioscli/usr/bin/nioscli
          cp debian/control debian_build_directory/nioscli/DEBIAN
          cat debian/control | envsubst > debian_build_directory/nioscli/DEBIAN/control

      - name: Build deb
        run: cd debian_build_directory && dpkg-deb --build nioscli

      - name: Rename deb file
        run: mv debian_build_directory/nioscli.deb debian_build_directory/nioscli-$VERSION.deb

      - uses: softprops/action-gh-release@v1
        with:
          files: |
            debian_build_directory/nioscli-${{ env.VERSION }}.deb
